/**
 * The sign-in bridge for the iOS app.
 *
 * Google refuses OAuth inside an app's web view, and native Google Sign-In
 * needs an iOS OAuth client registered in the Firebase console. This page is
 * the way round both: the app opens it in an ASWebAuthenticationSession — a
 * real Safari sheet, which Google allows — the coach signs in with the
 * website's own Firebase sign-in, and the page hands the resulting credential
 * back to the app, which exchanges it for a Firebase session of its own.
 *
 * Same project, same provider, same uid: the coach's teams are there the
 * moment the app finishes. See docs/ios/architecture.md.
 *
 * Two things here are security, not plumbing:
 *
 *  - The callback must be the app's own scheme. An attacker who could point
 *    `redirect` at a website would receive a Google ID token for whoever
 *    clicked their link. Anything that is not `inninggrid://` is refused.
 *  - `state` is generated by the app and must come back unchanged, so the app
 *    can tell a sign-in it started from one it did not.
 */

export const NATIVE_SCHEME = 'inninggrid:';

/** Only ever hand a credential back to the app itself. */
export function safeCallback(raw: string | null): URL | null {
  if (!raw) return new URL('inninggrid://auth');
  try {
    const url = new URL(raw);
    return url.protocol === NATIVE_SCHEME ? url : null;
  } catch {
    return null;
  }
}

/** `state` is a random token from the app: letters, digits and dashes only. */
export function safeState(raw: string | null): string | null {
  return raw && /^[A-Za-z0-9-]{16,128}$/.test(raw) ? raw : null;
}

export function callbackWith(base: URL, params: Record<string, string>): string {
  const url = new URL(base.toString());
  for (const [key, value] of Object.entries(params)) url.searchParams.set(key, value);
  return url.toString();
}
