/**
 * Bundles the shared core (src/core/api.ts) into one file for the iOS app.
 *
 *   node scripts/build_core.mjs
 *
 * The output runs inside JavaScriptCore, so it must be a single classic script
 * with no imports, no Node built-ins and no browser globals — esbuild's IIFE
 * format, assigned to `globalThis.InningGridCore`. The iOS build copies it from
 * apps/ios/InningGrid/Resources; re-run this after changing anything the core
 * imports, or the app ships yesterday's engine.
 */
import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const OUT = 'apps/ios/InningGrid/Resources/inninggrid-core.js';

await build({
  entryPoints: ['src/core/entry.ts'],
  bundle: true,
  format: 'iife',
  /* JavaScriptCore on iOS 17 — the app's floor — handles ES2022. */
  target: 'es2022',
  platform: 'neutral',
  outfile: OUT,
  alias: { '@': path.resolve('src') },
  /* Readable output: when the app reports an engine error, the stack points
     at a function name somebody can find, not a minified symbol. */
  minify: false,
  legalComments: 'none',
  logLevel: 'warning',
});

/*
  Stamp the bundle with a content hash, so the app can log exactly which
  engine produced a lineup — the first question when web and iOS disagree.
*/
const code = await readFile(OUT, 'utf8');
const hash = createHash('sha256').update(code).digest('hex').slice(0, 12);
await writeFile(OUT, `/* inninggrid-core ${hash} — generated by scripts/build_core.mjs; do not edit */\n${code}`);
console.log(`wrote ${OUT} (${(code.length / 1024).toFixed(0)} KB, ${hash})`);
