import type { TeamMembership } from '@/domain/access';
import { cloneFormation, getSystemFormation } from '@/domain/formations';
import { createGame, createPlayer, createTeam } from '@/domain/factories';
import type { Eligibility, Game, Player, Team } from '@/domain/types';
import { applyPhilosophy, defaultTeamSettings } from '@/domain/weights';
import { generateLineup, recordActualResults } from '@/services/lineupService';
import { emptyDatabase, type DugoutDatabase } from './localStore';

/**
 * Demo team (spec section 80): Balsam Waters, 11 players, six-inning baseball
 * with a ten-player defence.
 *
 * The four historical games are generated by the real optimizer and then
 * "played" with realistic interference — an absence, an early departure, a
 * game called after five innings, and a coach's in-game pitching change — so
 * the season dashboard shows genuine imbalance and the season-aware optimizer
 * has something real to compensate for.
 */

const FORMATION_ID = 'baseball-10-lc-rc';

interface SeedPlayerSpec {
  firstName: string;
  lastInitial: string;
  jersey: string;
  tier: 'CORE' | 'REGULAR' | 'DEVELOPING';
  offensiveTier?: 'CORE' | 'REGULAR' | 'DEVELOPING';
  canPitch: boolean;
  canCatch: boolean;
  preferredPitcher?: boolean;
  preferredCatcher?: boolean;
  preferred?: string[];
  avoid?: string[];
  never?: string[];
}

const SEED_PLAYERS: SeedPlayerSpec[] = [
  {
    firstName: 'Brody',
    lastInitial: 'Borek',
    jersey: '8',
    tier: 'CORE',
    canPitch: true,
    canCatch: true,
    preferredPitcher: true,
    preferred: ['P', '1B', 'SS'],
  },
  {
    firstName: 'Race',
    lastInitial: 'Smith',
    jersey: '12',
    tier: 'CORE',
    canPitch: true,
    canCatch: true,
    preferredPitcher: true,
    preferred: ['SS', 'P'],
  },
  {
    firstName: 'Weston',
    lastInitial: 'Jones',
    jersey: '4',
    tier: 'CORE',
    canPitch: true,
    canCatch: false,
    preferred: ['2B', 'CF'],
  },
  {
    firstName: 'Calvin',
    lastInitial: 'Miller',
    jersey: '7',
    tier: 'REGULAR',
    canPitch: true,
    canCatch: true,
    preferred: ['2B'],
  },
  {
    firstName: 'Emerson',
    lastInitial: 'Reed',
    jersey: '2',
    tier: 'REGULAR',
    canPitch: true,
    canCatch: true,
    preferred: ['3B'],
  },
  {
    firstName: 'Solomon',
    lastInitial: 'Fisk',
    jersey: '15',
    tier: 'REGULAR',
    canPitch: true,
    canCatch: false,
  },
  {
    firstName: 'Finnegan',
    lastInitial: 'Doyle',
    jersey: '21',
    tier: 'REGULAR',
    canPitch: true,
    canCatch: false,
    preferred: ['LF'],
  },
  {
    firstName: 'Vasil',
    lastInitial: 'Petrov',
    jersey: '9',
    tier: 'REGULAR',
    canPitch: false,
    canCatch: true,
    preferredCatcher: true,
    preferred: ['C'],
  },
  {
    firstName: 'Mehki',
    lastInitial: 'Barnes',
    jersey: '3',
    tier: 'DEVELOPING',
    canPitch: false,
    canCatch: true,
  },
  {
    firstName: 'Ashur',
    lastInitial: 'Haddad',
    jersey: '18',
    tier: 'DEVELOPING',
    canPitch: false,
    canCatch: false,
    // One of the two players who cannot cover first base.
    never: ['1B'],
  },
  {
    firstName: 'Walter',
    lastInitial: 'Nash',
    jersey: '24',
    tier: 'DEVELOPING',
    canPitch: false,
    canCatch: false,
    // The other; also new to the infield, so third base is a stretch.
    never: ['1B'],
    avoid: ['3B'],
  },
];

/**
 * Dates are offsets in days from today, never fixed strings.
 *
 * They used to be hardcoded to April 2026, which meant that by September the
 * demo opened on "No game scheduled" — a visitor's first impression of the
 * product was its empty state, and the whole point of the demo is the
 * populated one. Offsets keep the demo a season in progress forever.
 */
interface HistoricalGameSpec {
  /** Days before today. */
  daysAgo: number;
  opponent: string;
  seed: number;
  /** Innings actually played; a short game leaves fairness debt behind. */
  actualInnings: number;
  /** Players who missed the game entirely. */
  absent?: string[];
  /** First name -> last inning available. */
  leftEarly?: Record<string, number>;
  /** First name -> first inning available. */
  arrivedLate?: Record<string, number>;
  pitchingPlan?: Record<number, string>;
}

const HISTORY: HistoricalGameSpec[] = [
  {
    daysAgo: 28,
    opponent: 'Cubs',
    seed: 101,
    actualInnings: 6,
    pitchingPlan: { 1: 'Race', 2: 'Brody' },
  },
  {
    daysAgo: 21,
    opponent: 'Braves',
    seed: 202,
    actualInnings: 6,
    // Walter misses a whole game, which is exactly the kind of gap the
    // season-aware optimizer must not treat as debt.
    absent: ['Walter'],
    pitchingPlan: { 1: 'Weston', 2: 'Calvin' },
  },
  {
    daysAgo: 14,
    opponent: 'Cardinals',
    seed: 303,
    // Called after five innings: inning six counts for nothing.
    actualInnings: 5,
    leftEarly: { Mehki: 3 },
    pitchingPlan: { 1: 'Brody', 2: 'Race', 3: 'Solomon' },
  },
  {
    daysAgo: 7,
    opponent: 'Pirates',
    seed: 404,
    actualInnings: 6,
    arrivedLate: { Ashur: 3 },
    pitchingPlan: { 1: 'Emerson', 2: 'Finnegan' },
  },
];

/** A local calendar date, `n` days from today. Local, not UTC: a coach's
    Saturday game must not land on Friday for anyone west of Greenwich. */
function dateOffset(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(
    d.getDate(),
  ).padStart(2, '0')}`;
}

export const DEMO_TEAM_NAME = 'Balsam Waters';

export async function buildDemoDatabase(): Promise<DugoutDatabase> {
  const formation = cloneFormation(getSystemFormation(FORMATION_ID)!);
  const positionIdByCode = new Map(formation.positions.map((p) => [p.code, p.id]));

  const settings = applyPhilosophy(
    {
      ...defaultTeamSettings(),
      minDefensiveInnings: 4,
      minDefensiveInningsMode: 'TARGET',
      infieldOpportunity: { mode: 'TARGET', innings: 1 },
      maxPitchingInningsPerPlayer: 2,
    },
    'BALANCED',
  );

  const team: Team = createTeam({
    name: DEMO_TEAM_NAME,
    sport: 'BASEBALL',
    division: 'Little League Minors',
    seasonName: 'Spring 2026',
    defaultInnings: 6,
    defaultFormationId: formation.id,
    settings,
  });

  const players: Player[] = SEED_PLAYERS.map((spec, index) => {
    const player = createPlayer({
      teamId: team.id,
      firstName: spec.firstName,
      lastInitial: spec.lastInitial,
      jerseyNumber: spec.jersey,
      overallTier: spec.tier,
      offensiveTier: spec.offensiveTier ?? spec.tier,
      canPitch: spec.canPitch,
      canCatch: spec.canCatch,
      createdAt: new Date(Date.UTC(2026, 2, 1, 12, 0, index)).toISOString(),
    });
    player.preferredPitcher = spec.preferredPitcher ?? false;
    player.preferredCatcher = spec.preferredCatcher ?? false;

    const rate = (code: string, eligibility: Eligibility) => {
      const positionId = positionIdByCode.get(code);
      if (!positionId) return;
      player.positionRatings[positionId] = { positionId, eligibility };
    };
    for (const code of spec.never ?? []) rate(code, 'NEVER');
    for (const code of spec.avoid ?? []) rate(code, 'AVOID');
    for (const code of spec.preferred ?? []) rate(code, 'PREFERRED');

    return player;
  });

  const playerByName = new Map(players.map((player) => [player.firstName, player]));
  const games: Game[] = [];

  for (const spec of HISTORY) {
    const game = createGame({
      teamId: team.id,
      opponent: spec.opponent,
      date: dateOffset(-spec.daysAgo),
      plannedInnings: 6,
      formation,
      settings,
      players,
      seed: spec.seed,
    });

    game.gamePlayers = game.gamePlayers.map((gp) => {
      const player = players.find((p) => p.id === gp.playerId)!;
      const absent = spec.absent?.includes(player.firstName) ?? false;
      return {
        ...gp,
        available: !absent,
        arrivalInning: spec.arrivedLate?.[player.firstName],
        departureInning: spec.leftEarly?.[player.firstName],
      };
    });

    for (const [inning, name] of Object.entries(spec.pitchingPlan ?? {})) {
      const pitcher = playerByName.get(name);
      if (pitcher) game.pitchingPlan[Number(inning)] = pitcher.id;
    }

    const { result, game: planned } = await generateLineup({
      team,
      game,
      players,
      history: games,
    });

    if (!result.ok) {
      // A demo game that cannot be generated is a bug, but it must never block
      // the app from starting: record the game without a lineup and move on.
      games.push({ ...game, status: 'COMPLETED', actualInnings: spec.actualInnings });
      continue;
    }

    games.push(recordActualResults(planned, spec.actualInnings));
  }

  /*
    The upcoming game Home points at. Three days out, so the demo always shows
    a game being prepared rather than one already played.

    Attendance is deliberately left unconfirmed: the first thing a visitor
    should meet is the actual workflow — confirm who is here, then generate —
    not a lineup that already exists with no explanation of where it came from.
  */
  const upcoming = createGame({
    teamId: team.id,
    opponent: 'Cardinals',
    date: dateOffset(3),
    plannedInnings: 6,
    formation,
    settings,
    players,
    seed: 1,
  });

  const headCoach: TeamMembership = {
    id: 'mem_head_coach',
    teamId: team.id,
    userId: 'user_demo',
    email: 'coach@balsamwaters.example',
    name: 'Head Coach',
    role: 'HEAD_COACH',
    status: 'ACTIVE',
    createdAt: team.createdAt,
  };

  return {
    ...emptyDatabase(),
    teams: [team],
    players,
    games: [...games, upcoming],
    memberships: [headCoach],
  };
}
